### PR TITLE
Update global reduction implementation to improve performance, fix VP bug

### LINKED ISSUE #780: Refactor global sums to improve performance
The global sums have traditionally been used only for diagnostics in the log file.  The VP solver now also uses global sums, see #774.  The CICE generic global sums could be refactored to improve performance, shifting if statements associated with optional arguments relative to loops and similar.

### PR DESCRIPTION
**Pull request by apcraig**
## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Update global reduction implementation to improve performance, fix VP bug
- [X] Developer(s): 
    apcraig
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    All tests are bit-for-bit on cheyenne except VP which changed answers due to fix in workspace_y calculation and haloupdate in the preconditioner.  sumchk tests fail regression due to some new output in the log file, not significant.  https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#942449751275ebd884abb5752d03d7ea64b72664
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit except VP
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR update the Icepack submodule?  If so, the Icepack submodule must point to a hash on Icepack's main branch.
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [X] Yes
    - [ ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [X] Please provide any additional information or relevant details below:

This was mainly done for situations like VP that need a fast global sum. The VP global sum is still slightly faster than the one computed in the infrastructure, so kept that implementation.  Found a bug in the workspace_y calculation in VP that was fixed.  Also found that the haloupdate call as part of the precondition step generally improves VP performance, so removed option to NOT call the haloupdate there.

Separately, fixed a bug in the tripoleT global sum implementation, added a tripoleT global sum unit test, and resynced ice_exit.F90, ice_reprosum.F90, and ice_global_reductions.F90 between serial and mpi versions.

- Refactor global sums to improve performance, move if checks outside do loops
- Fix bug in tripoleT global sums, tripole seam masking
- Update VP solver, use local global sum more often
- Update VP solver, fix bug in workspace_y calculation
- Update VP solver, always call haloupdate during precondition
- Refactor ice_exit.F90 and sync serial and mpi versions
- Sync ice_reprosum.F90 between serial and mpi versions
- Update sumchk unit test to handle grids better
- Add tripoleT sumchk test

Closes #780

### CODE REVIEW

**Comment by phil-blain** [comment]
Thanks a lot Tony for working on this. I'm really swamped with other things right now so I won't have time to review this PR more closely, but I gave it a quick look and the changes look fine. Your justification looks also OK for the first change in ice_dyn_vp.

We'll check how the solver scales eventually and might revisit these choices at that point, but for now what you did is a nice improvement.

**Review by eclare108213 — COMMENTED** [review]
This looks good to me.  I'd only ask @JFLemieux73 to confirm that the VP bug fix for the workspace_y calculation is correct.  Thanks!

**Comment by apcraig** [comment]
Closes #780

**Comment by phil-blain** [comment]
> Closes https://github.com/CICE-Consortium/CICE/issues/780

I think this has to go in the description, or the commit message for the issue to be closed automatically.

File: cicecore/cicedyn/dynamics/ice_dyn_vp.F90 [hunk 1]
```diff
@@ -2552,8 +2552,14 @@ function global_dot_product (nx_block  , ny_block , &
...
 
-      ! Use local summation result unless bfbflag is active
-      if (bfbflag == 'off') then
+      ! Use faster local summation result for several bfbflag settings.
+      ! The local implementation sums over each block, sums over local
+      ! blocks, and calls global_sum on a scalar and should be just as accurate as
+      ! bfbflag = 'off', 'lsum8', and 'lsum4' without the extra copies and overhead
+      ! in the more general array global_sum.  But use the array global_sum
+      ! if bfbflag is more strict or for tripole grids (requires special masking)
+      if (ns_boundary_type /= 'tripole' .and. ns_boundary_type /= 'tripoleT' .and. &
```
Comment (apcraig) [inline cicecore/cicedyn/dynamics/ice_dyn_vp.F90:2561]: Just added this check on tripole grids.  Don't want to use the local sum with tripole grids because special masking is required.  Reran full test suite on cheyenne with gnu compiler and should be good.

**Comment by apcraig** [comment]
One other note.  The VP solver is 10%-15% faster when using the local global sum.  The differences was more like 30% before the updates to the global sum implementation, but it still doesn't match the local implementation.  That's why it's still there.

**Comment by phil-blain** [comment]
This is still a great improvement. Thanks a lot for this effort!

**Review by JFLemieux73 — APPROVED** [review]
@phil-blain and I just had a chat about this. We think everything is ok. Thanks Tony for your help.

**Comment by apcraig** [comment]
Thanks everyone, will merge when GHActions completes successfully.
